import 'dart:convert';

import 'package:flutter/foundation.dart';
import 'package:weather_app/Models/weather%20respnse.dart';
import 'package:weather_app/secrets/api.dart';
import 'package:http/http.dart' as http;

class WeatherServiceProvider extends ChangeNotifier {
  Autogenerated? _weather;

  Autogenerated? get weather => _weather;

  bool _isloading = false;
  bool get isLoading => _isloading;

  String _error = "";
  String get error => _error;

  Future<void> fetchWeatherDataByCity(String city) async {
    _isloading = true;
    _error = "";

    try {
      //https://api.openweathermap.org/data/2.5/weather?q=Dubai&appid=4d746cceda99601073343183a8e8f270&units=metric

      final String apiUrl =
          "${APIendpoints().cityUrl}${city}&appid=${APIendpoints().api_key}${APIendpoints().unit}";
       print(apiUrl);
      final response = await http.get(Uri.parse(apiUrl));

      if (response.statusCode == 200) {
        final data = jsonDecode(response.body);

        print(data);

        _weather = Autogenerated.fromJson(data);
        print(_weather!.name);
        notifyListeners();
      } else {
        _error = "Failed to load data";
      }
    } catch (e) {
      _error = "Failed to load data";
    } finally {
      _isloading = false;
      notifyListeners();
    }
  }
}
